spring:
  application:
    name: Ralali_API

ralali:
  api:
    base-url: https://apigw.ralali.com
    sellers-endpoint: /search/v3/sellers
    items-endpoint: /search/v3/items
    auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOjEwMDAwLCJ0b2tlbl92ZXJzaW9uIjoiMS4wLjAiLCJ0b2tlbl90eXBlIjoiZ3Vlc3RfdG9rZW4iLCJhdWQiOiIxMSIsImV4cCI6MTc0NjY3MDEyNSwianRpIjoiN2YzMWI3MTQtYTRlMS0wNGVkLTBmNWEtZDExYmJkZGY0YzczIiwiaWF0IjoxNzQ2NTgzNzI1LCJpc3MiOiIvZXgvdjMvdG9rZW4ifQ.Oy0PcCJuJzF7ee2v17O30-9IRCHIh-dHAIQPFGnBMvs42ZhcNeUktUn_tXK1bpKoIHVBzWm78fd619xt897mv0JaLmAGHuCkZHtQm_SnwJBsZsGS9QKRxBFMZcbqbDgsmpSFqbI3FTtw6Wc9FsG1cGOy2fiAiw8JAAnGxW2b7cPKL9lIGAS6bbRYXiBYd0o9-VCijvAdvXxVxpH79Phv7c2SFVXgjBEqF9mbNthRELAng_15i6vgRs3xnwLb4HtM5Y6oVhcwN_Yd1RQQ4GfNJDB-HiDljeZAwnmSze1UuUP42F8F7HUGJGX7TJfIejXrDpYJpesPXFOuuI-Gt8USqg
    guest-id: defd5756-0b0c-4271-a6c6-9f5dfb4d1d86
    query-params:
      is-personal-courier: false
      is-wholesale: false
      limit: 20
      max-price: 10000000000
      min-price: 1
      order-by: match
      page: 1